-- THIS SCRIPT IS NEEDED TO LOAD SLMP RESOURCES
-- PLEASE, DO NOT DELETE IT IF YOU WANT TO USE SLMP
script.load(getWorkingDirectory().."\\resource\\Simple MP\\init.lua")
-- SLMP INIT SCRIPT WILL LOAD EVERYTHING YOU NEED TO PLAY
-- PLEASE DO NOT DELETE FILES FROM DIRECTORY RESOURCE\\SIMPLE MP