PACKET =
{
  CONFIRM_RECEIVING = 1,
  CONNECTION_REQUEST = 2,
  CONNECTION_REQUEST_FAIL = 3,
  CONNECTION_REQUEST_SUCCESS = 4,
  UPDATE_STREAM = 5,
  ONFOOT_SYNC = 6,
  PING_SERVER = 7,
  DISCONNECT_NOTIFICATION = 8
}

RPC =
{
  PLAYER_CONNECT = 1,
  PLAYER_DISCONNECT = 2,
  UPDATE_PING_AND_SCORE = 3,
  SET_PLAYER_SKIN = 4,
  SET_PLAYER_POS = 5,
  SET_PLAYER_INTERIOR = 6,
  SET_PLAYER_ANGLE = 7,
  SEND_MESSAGE = 8,
  SEND_COMMAND = 9,
  SET_CHAT_BUBBLE = 10,
  SHOW_DIALOG = 11,
  DIALOG_RESPONSE = 12
}

GAMESTATE =
{
  ONFOOT = 1
}